jobs:
  include:
    - stage: test
      language: node_js
      cache: npm
      install:
        - npm ci
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
          > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - './cc-test-reporter before-build'
      script:
        - npm run lint
        - npm run test:once -- --coverage
      after_script:
        - './cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT'
    - stage: release
      language: node_js
      services:
        - docker
      install:
        - bash ./infrastructure/travis/install-openshift.sh
        - export PATH=$PATH:/tmp/openshift
        - npm i -D @semantic-release/commit-analyzer @semantic-release/release-notes-generator
          @semantic-release/github @semantic-release/exec semantic-release-docker
      script:
        - docker build -t jobtechswe/myskills-web
          --build-arg REACT_APP_GRAPHQL_URI=$REACT_APP_GRAPHQL_URI
          --build-arg REACT_APP_GRAPHQL_WS_URI=$REACT_APP_GRAPHQL_WS_URI
          .
        - npx semantic-release
stages:
  - test
  - name: release
    if: branch = master
before_install:
  - openssl aes-256-cbc -K $encrypted_6b48726482ce_key -iv $encrypted_6b48726482ce_iv
    -in ./infrastructure/travis/openshift-token.enc -out ./infrastructure/travis/openshift-token -d
notifications:
  slack:
    on_pull_requests: false
    on_success: never
    on_failure: always
    rooms:
      - secure: EIhVhqeEpqRDzR68DT3wWLtnBCaX913KG7po89dXZi77yWNX9/aFdtXT3RpwY1RXdOUhoeTd5wkEvf6eZSbVz541jGCg+uZrJCKWjy3yS1bCZauQOnQ4qBTPwlue2CMZrvF9lKjrYsgisK6dAp/6cRAsdqM1N7M1OPI1BrRuG6aH/td8MAU8gm1VFSqZhvFcgQxwbs8TQxhBc7gJsi2qvlYHp4mEfVynrKOkvJ/lhEhv+0MnRhpspC3CmpStoDlPm5WdrlYfIleLHbWbmQtxwQ++GF5ic34jBaHh4zNrBB6e3VzgOzvBzrI/E8Ub8UEkA0VOE/5Q90zrQuOd5RDtOXG13J/8ZyLWqdAvs3puOlqjAuEMU+xhPMHdyLYHrBSEWbXMkPpT9qN8WBWdFoGTqRAIOIhV+FhEpp0kV2X3UukLwn0RHpi96weSVFVTi9DmF7JShvoGKECwrEI96JbsMt0KdOluOnbUiExPk7zO8v6ADLy2469ewrRI+OcDZyyxy3mgeH/lSYPgRyo0QAvwOJJBJSfvhvv/Abej3AFy9G9Fr1csITg1QJV9mpU2wIKxDYLSS8WkaEkA0sHruU3LR1SnWaIeQMFHCEVUzteIY3pz29QuUlNGqGnl3k9oZLRY1++cDaJcW6imzVm5nrccaIZq9zw1t8XFrEGQy86YHtk=
    template:
      - Repo `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>)
        for commit (<%{compare_url}|%{commit}>) on branch `%{branch}`.
      - 'Message: %{commit_message}'
      - 'Execution time: *%{duration}*'
