jobs:
  include:
    - stage: test
      language: node_js
      cache: npm
      install:
        - npm ci
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
          > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - './cc-test-reporter before-build'
      script:
        - npm run lint
        - npm run test:once -- --coverage
      after_script:
        - './cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT'

    - stage: build
      install: skip
      services:
        - docker
      script:
        - bash ./infrastructure/travis/build.sh
    - stage: deploy
      before_install:
        - openssl aes-256-cbc -K $encrypted_bea024308360_key -iv $encrypted_bea024308360_iv
          -in ./infrastructure/travis/openshift-token.enc -out ./infrastructure/travis/openshift-token
          -d
      install:
        - bash ./infrastructure/travis/install-openshift.sh
        - export PATH=$PATH:/tmp/openshift
      script: bash ./infrastructure/travis/deploy.sh
stages:
  - test
  - name: build
    if: '(branch = master AND type != pull_request) OR tag IS present'
  - name: deploy
    if: '(branch = master AND type != pull_request) OR tag IS present'
notifications:
  slack:
    on_pull_requests: false
    on_success: never
    on_failure: always
    rooms:
      - secure: SvmmxolNZkI1pee+sg/fpQlLdFt5j5/tXV/NFN4ls0Nkjp4Y1UYVtFCJF8n6OOJj0qxg+mebsZB3QZ6OGkhbrQxwGP7zt7f5d4SExW7+hur5c+8K+s/5n9zCAe27RCtReOcYiDqDI4/36ke9BU+wjz0gqG8pND8n8G/ThezwWjrHH6k6/d7Zc4HcZftDwN+HVrMHanboR2L3RO8HZICSSFTrC79pXq3pojmsKP+SQMwDjTFcYh8WSHSUeFrjtugh7DgKRkyqOInbASmp92cxlu/lA2obnP8zzuW1YecNDd556QDq2IiJKytfQakDMrzLpSFRoXr60mqX3zYAnRAPra15gKfv5Ojcc/pFsCTUzzDC8Xx4Tov3DQsOg6Hxf4D72uVf9f+KvQcRAv6tkELk3jsOIOYHvEz23HYoMmI+VrlE1FLaXPixisfigOOQuYmt2QnyJA8I9P/SEshBDNW2sVKHrWUGdVtfwd8myl8fKiSe4JyKFlV8myhOCoku6SL8ZVLpAB/yjSUDpSm1zw9FCzOHZjUAB6OgcI2FSkE1V8+awI1J3GRjh5PPl4tLfzh19exGdgn2ENatnRtY/gb6vWP6Fvn42DND4n4ujXNxBKTmz+gsPzvd1eC8xkAfpTcOvSiyCNyzK+/lNNCZxWW6z5C9NjTNYK7NDBWSN6kckKI=
    template:
      - 'Repo `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch `%{branch}`.'
      - 'Message: %{commit_message}'
      - 'Execution time: *%{duration}*'
